{
    "openapi":"3.0.2",
    "info": {
      "title":"API Title",
      "version":"1.0"
    },
    "servers": [
      {"url":"http://localhost:3000"}
    ],
    "components": {
      "schemas": {
        "cinema": {
          "required": [
            "id", "Name", "Address", "ProvinceCity"
          ],
          "allOf": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "description": "The auto-generated id of cinema"
                }
              }
            },
            {
              "$ref": "#/components/schemas/cinemaWithoutId"
            }
          ],
          "example": {
            "id": 1, 
            "name": "CGV",
            "address": "123 Nguyen Ba Hoc",
            "provinceCity": {
              "id": 1,
              "name": "Da Nang"
            }
          }
        },
        "provinceCity": {
          "type": "object",
          "required": [
            "id", "Name"
          ],
          "properties": {
            "id": {
              "type": "integer",
              "description": "The auto-generated id of province/city"
            },
            "name": {
              "type": "string",
              "description": "Name of province/city"
            }
          }
        },
        "provinceCityWithCinema": {
          "type": "object",
          "required": [
            "id", "Name"
          ],
          "properties": {
            "id": {
              "type": "integer",
              "description": "The auto-generated id of province/city"
            },
            "name": {
              "type": "string",
              "description": "Name of province/city"
            },
            "cinemas": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/cinema"
              }
            }
          },
          "example": {
            "id": 1,
            "name": "Da Nang",
            "cinemas": [
              {
                "id": 1,
                "name": "CGV",
                "address": "123 Nguyen Ba Hoc",
                "provinceCityId": 1
              },
              {
                "id": 2,
                "name": "VGC",
                "address": "321 Nguyen Ba Hoc",
                "provinceCityId": 1
              }
            ]
          }
        },
        "screen": {
          "required": [
            "id"
          ],
          "allOf": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "description": "The auto-generated id of screen"
                }
              }
            },
            {
              "$ref": "#/components/schemas/screenWithoutId"
            }
          ],
          "example": {
            "id": 1,
            "seatMatrix": "./screen1.txt",
            "cinemaId": 1
          }
        },
        "screenWithoutId": {
          "type": "object",
          "required": [
            "seatMatrix", "cinemaId"
          ],
          "properties": {
            "seatMatrix": {
              "type": "string",
              "description": "Path of file seat matrix"
            },
            "cinemaId": {
              "type": "integer",
              "description": "The id of cinema"
            }
          },
          "example": {
            "seatMatrix": "./screen1.txt",
            "cinemaId": 1
          }
        },
        "cinemaWithoutId": {
          "type": "object",
          "required": [
            "name", "address", "provinceCityId"
          ],
          "properties": {
            "name": {
              "type": "string",
              "description": "Name of cinema"
            },
            "address": {
              "type": "string",
              "description": "Address of cinema"
            },
            "provinceCityId": {
              "type": "integer",
              "description": "Id of province/city"
            }
          },
          "example": {
            "name": "CGV",
            "address": "123 Nguyen Ba Hoc",
            "provinceCityId": 1
          }
        },
        "show": {
          "required": [
            "id"
          ],
          "allOf": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "description": "The auto-generated id of show"
                }
              }
            },
            {
              "$ref": "#/components/schemas/showWithoutId"
            }
          ],
          "example": {
            "id": 1,
            "filmId": 1,
            "screenId": 1,
            "timeStart": "2024-06-25",
            "price": 300,
            "seatMatrix": "./seatMatrix.txt",
            "formatId": 1,
            "subtitle": true,
            "dubbing": true
          }
        },
        "showWithoutId": {
          "required": [
            "filmId",
            "screenId", 
            "timeStart",
            "price", 
            "seatMatrix", 
            "formatId", 
            "subtitle", 
            "dubbing"
          ],
          "type": "object",
          "properties": {
            "filmId": {
              "type": "integer",
              "description": "The film's id of this show"
            },
            "screenId": {
              "type": "integer",
              "description": "The screen's id of this show"
            },
            "timeStart": {
              "type": "string",
              "description": "The start time of this show"
            },
            "price": {
              "type": "integer",
              "description": "The price of this show"
            },
            "seatMatrix": {
              "type": "string",
              "description": "Path of file seat matrix"
            },
            "formatId": {
              "type": "integer",
              "description": "The id of format"
            },
            "subtitle": {
              "type": "boolean",
              "description": "True is have subtitle, false is have not subtile"
            },
            "dubbing": {
              "type": "boolean",
              "description": "True is have dubbing, false is have not dubbing"
            }
          },
          "example": {
            "filmId": 1,
            "screenId": 1,
            "timeStart": "2024-06-25",
            "price": 300,
            "seatMatrix": "./seatMatrix.txt",
            "formatId": 1,
            "subtile": true,
            "dubbing": true
          }
        },
        "film": {
          "required": ["id"],
          "allOf": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "description": "The auto-generated id of film"
                }
              }
            },
            {
              "$ref": "#/components/schemas/filmWithoutId"
            }
          ],
          "example": {
            "id": 1,
            "filmName": "Absolute cinema",
            "duration": 300,
            "dateSrart": "2024-06-25",
            "dateEnd": "2024-06-26",
            "director": "Absolute director",
            "actor": "Absolute actors",
            "subtile": true,
            "language": "English",
            "rateId": 1,
            "poster": "./poster.jpeg",
            "trailer": "./trailer.mp4"
          }
        },
        "filmWithoutId": {
          "required": [
            "filmName",
            "duration",
            "dateStart",
            "dateEnd",
            "director",
            "actor",
            "subtile",
            "language",
            "rateId",
            "poster",
            "trailer"
          ],
          "type": "object",
          "properties": {
            "filmName": {
              "type": "string",
              "description": "The name of film"
            },
            "duration": {
              "type": "integer",
              "description": "The duration of film"
            },
            "dateStart": {
              "type": "string",
              "description": "The date start of film"
            },
            "dateEnd": {
              "type": "string",
              "description": "The date start of film"
            },
            "director": {
              "type": "string",
              "description": "The director of film"
            },
            "actor": {
              "type": "string",
              "description": "The actors of film"
            },
            "subtile": {
              "type": "boolean",
              "description": "True when film have subtitle"
            },
            "language": {
              "type": "string",
              "description": "The language of film"
            },
            "rateId": {
              "type": "integer",
              "description": "The rate of the film"
            },
            "poster": {
              "type": "string",
              "description": "The path of the poster file"
            },
            "trailer": {
              "type": "string",
              "description": "The path of the trailer video"
            }
          },
          "example": {
            "filmName": "Absolute cinema",
            "duration": 300,
            "dateSrart": "2024-06-25",
            "dateEnd": "2024-06-26",
            "director": "Absolute director",
            "actor": "Absolute actors",
            "subtile": true,
            "language": "English",
            "rateId": 1,
            "poster": "./poster.jpeg",
            "trailer": "./trailer.mp4"
          }
        },
        "error": {
          "type": "object",
          "properties": {
            "status": {
              "type": "integer"
            },
            "message": {
              "type": "string"
            }
          }
        },
        "cinemaDto": {
          "required": [
            "id",
            "poster",
            "ageRating",
            "format",
            "title",
            "trailerLink",
            "category",
            "nation", 
            "subtitle",
            "duration"
          ],
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "poster": {
              "type": "string"
            },
            "ageRating": {
              "type": "string"
            },
            "format": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "trailerLink": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "nation": {
              "type": "string"
            },
            "subtitle": {
              "type": "string"
            },
            "duration": {
              "type": "integer"
            }
          },
          "example": {
            "id": 1,
            "poster": "./poster.img",
            "ageRating": "PG-13",
            "format": "2D",
            "title": "Movie Name",
            "trailerLink": "./trailer.mp4",
            "category": "Drama",
            "nation": "Vietnam",
            "subtitle": "VN",
            "duration": 127
          }
        }
      },
      "responses": {
        "FilmResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/film"
              }
            }
          }
        },
        "ListFilmResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/film"
                }
              }
            }
          }
        },
        "CinemaResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/cinemaDto"
              }
            }
          }
        },
        "ListCinemaResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/cinemaDto"
                }
              }
            }
          }
        },
        "ScreenResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/screen"
              }
            }
          }
        },
        "ListScreenResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/screen"
                }
              }
            }
          }
        },
        "ShowResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/show"
              }
            }
          }
        },
        "ListShowResponse": {
          "description": "OK",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/show"
                }
              }
            }
          }
        },
        "404-NotFound": {
          "description": "Not Found",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/error"
              }
            }
          }
        },
        "400-BadRequest": {
          "description": "Bad Request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/error"
              }
            }
          }
        },
        "500-ServerError": {
          "description": "Internal Server Error",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/error"
              }
            }
          }
        },
        "ProvinceResponse": {
          "description": "Province with list cinema",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/provinceCityWithCinema"
                }
              }
            }
          }
        }
      },
      "parameters": {
        "CinemaPath": {
          "name": "cinemaId",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          },
          "description": "Cinema's id",
          "example": 10,
          "style": "simple",
          "explode": false
        },
        "ScreenPath": {
          "name": "screenId",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          },
          "description": "Screen's id",
          "example": 10,
          "style": "simple",
          "explode": false
        },
        "ShowPath": {
          "name": "showId",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          },
          "description": "Show's id",
          "example": 10,
          "style": "simple",
          "explode": false
        },
        "FilmQuery": {
          "name": "filmId",
          "in": "query",
          "required": false,
          "schema": {
            "type": "integer"
          },
          "description": "The id of film\n\n?filmId=10",
          "example": 10,
          "style": "form",
          "explode": false
        },
        "ScreenQuery": {
          "name": "screenId",
          "in": "query",
          "required": false,
          "schema": {
            "type": "integer"
          },
          "description": "The id of screen\n\n?screenId=10",
          "example": 10,
          "style": "form",
          "explode": false
        },
        "DateTime": {
          "name": "dateTime",
          "in": "query",
          "required": false,
          "schema": {
            "type": "string"
          },
          "description": "The date time\n\n?dateTime=2024-01-01 00:00:00",
          "example": "2024-01-01 00:00:00",
          "style": "form"
        },
        "Date": {
          "name": "date",
          "in": "query",
          "required": false,
          "schema": {
            "type": "string"
          },
          "description": "The date"
        },
        "CinemaQuery": {
          "name": "cinemaId",
          "in": "query",
          "required": false,
          "schema": {
            "type": "integer"
          },
          "description": "The id of cinema\n\n?cinemaId=10",
          "example": 10
        },
        "FilmPath": {
          "name": "filmId",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          },
          "description": "The id of film"
        }
      },
      "requestBodies": {
        "cinemaWithoutIdBody": {
          "description": "Cinema information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/cinemaWithoutId"
              }
            }
          }
        },
        "cinemaBody": {
          "description": "Cinema information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "id",
                  "name",
                  "address",
                  "provinceCityId"
                ],
                "properties": {
                  "id": {
                    "type": "integer",
                    "description": "The id of cinema"
                  },
                  "name": {
                    "type": "string",
                    "description": "Name of cinema"
                  },
                  "address": {
                    "type": "string",
                    "description": "Address of cinema"
                  },
                  "provinceCityId": {
                    "type": "integer",
                    "description": "Id of province/city"
                  }
                },
                "example": {
                  "id": 1,
                  "name": "CGV",
                  "address": "123 Nguyen Ba Hoc",
                  "provinceCityId": 1
                }
              }
            }
          }
        },
        "screenBody": {
          "description": "Screen information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/screen"
              }
            }
          }
        },
        "screenWithoutIdBody": {
          "description": "Screen information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/screenWithoutId"
              }
            }
          }
        },
        "showBody": {
          "description": "Show information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/show"
              }
            }
          }
        },
        "showWithoutIdBody": {
          "description": "Show information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/showWithoutId"
              }
            }
          }
        },
        "filmBody": {
          "description": "Film information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/film"
              }
            }
          }
        },
        "filmWithoutIdBody": {
          "description": "Film information",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/filmWithoutId"
              }
            }
          }
        }
      }
    },
    "paths": {
      "/cinema": {
        "get": {
          "tags": [
            "Cinema"
          ],
          "description": "Get list cinemas from database",
          "parameters": [
            {
              "name": "provinceCityId",
              "in": "query",
              "schema": {
                "type": "integer"
              },
              "required": false,
              "description": "Province/city id to get list cinema by province/city\n\n?provinceCityId=10",
              "example": "10",
              "style": "form",
              "explode": false
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ListCinemaResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "post": {
          "description": "Add cinema into database",
          "tags": ["Cinema"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/cinemaBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "400": {
              "$ref": "#/components/responses/400-BadRequest"
            }, 
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "put": {
          "description": "Update cinema information ",
          "tags": ["Cinema"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/cinemaWithoutIdBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/cinema/{cinemaId}": {
        "get": {
          "tags": [
            "Cinema"
          ],
          "description": "Get cinema's information",
          "parameters": [
            {
              "$ref": "#/components/parameters/CinemaPath"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/CinemaResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "delete": {
          "description": "Delete cinema from database",
          "tags": ["Cinema"],
          "parameters": [
            {
              "$ref": "#/components/parameters/CinemaPath"
            }
          ],
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        } 
      },
      "/screen": {
        "get": {
          "description": "Get list screens from database",
          "tags": ["Screen"],
          "parameters": [
            {
              "$ref": "#/components/parameters/CinemaQuery"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ListScreenResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "post": {
          "description": "Add cinema into database",
          "tags": ["Screen"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/screenWithoutIdBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "400": {
              "$ref": "#/components/responses/400-BadRequest"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "put": {
          "description": "Update screen information",
          "tags": ["Screen"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/screenBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/screen/{screenId}": {
        "get": {
          "description": "Get screen information by screen id",
          "tags": ["Screen"],
          "parameters": [
            {
              "$ref": "#/components/parameters/ScreenPath"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ScreenResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/show": {
        "get": {
          "description": "Get list of show",
          "tags": ["Show"],
          "parameters": [
            {
              "$ref": "#/components/parameters/FilmQuery"
            },
            {
              "$ref": "#/components/parameters/CinemaQuery"
            },
            {
              "$ref": "#/components/parameters/ScreenQuery"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ListShowResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "post": {
          "description": "Add new show into database",
          "tags": ["Show"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/showWithoutIdBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "400": {
              "$ref": "#/components/responses/400-BadRequest"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "put": {
          "description": "Update show information",
          "tags": ["Show"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/showBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            }, 
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/show/{showId}": {
        "get": {
          "description": "Get show information",
          "tags": ["Show"],
          "parameters": [
            {
              "$ref": "#/components/parameters/ShowPath"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ShowResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/film": {
        "get": {
          "description": "Get list of film",
          "tags": ["Film"],
          "parameters": [
            {
              "$ref": "#/components/parameters/CinemaQuery"
            },
            {
              "$ref": "#/components/parameters/Date"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ListFilmResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "post": {
          "description": "Add film to database",
          "tags": ["Film"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/filmWithoutIdBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "400": {
              "$ref": "#/components/responses/400-BadRequest"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        },
        "put": {
          "description": "Update film information",
          "tags": ["Film"],
          "parameters": [],
          "requestBody": {
            "$ref": "#/components/requestBodies/filmBody"
          },
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/film/{filmId}": {
        "get": {
          "description": "Get inforamtion of film",
          "tags": ["Film"],
          "parameters": [
            {
              "$ref": "#/components/parameters/FilmPath"
            }
          ],
          "responses": {
            "200": {
              "$ref": "#/components/responses/FilmResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      },
      "/provinceCity": {
        "get": {
          "description": "Get list province with list cinema",
          "tags": ["Province/City"],
          "parameters": [],
          "responses": {
            "200": {
              "$ref": "#/components/responses/ProvinceResponse"
            },
            "404": {
              "$ref": "#/components/responses/404-NotFound"
            },
            "500": {
              "$ref": "#/components/responses/500-ServerError"
            }
          }
        }
      }
    }
}